# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bogie/v1/bogie.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bogie/v1/bogie.proto',
  package='bogie',
  syntax='proto3',
  serialized_options=b'Z\010bogie/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x62ogie/v1/bogie.proto\x12\x05\x62ogie\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n\x16VibrationSensorSamples\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x33\n\x0f\x66irst_sample_ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x01\x12\x0f\n\x07samples\x18\n \x03(\x02\"\xe8\x02\n\x05\x42ogie\x12\n\n\x02id\x18\x01 \x01(\x05\x12(\n\x0ctrigger_type\x18\x02 \x01(\x0e\x32\x12.bogie.TriggerType\x12.\n\ntrigger_ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x0csteady_drive\x18\x04 \x01(\x0b\x32\x18.bogie.Bogie.SteadyDrive\x12\'\n\x08position\x18\x05 \x01(\x0b\x32\x15.bogie.Bogie.Position\x12\x35\n\x0esensor_samples\x18\n \x03(\x0b\x32\x1d.bogie.VibrationSensorSamples\x1a\'\n\x0bSteadyDrive\x12\x0b\n\x03max\x18\x01 \x03(\x01\x12\x0b\n\x03rms\x18\x02 \x03(\x01\x1a@\n\x08Position\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01*A\n\x0bTriggerType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06MANUAL\x10\x01\x12\x19\n\x15TRIGGER_CONDITION_MET\x10\x02\x42\nZ\x08\x62ogie/v1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_TRIGGERTYPE = _descriptor.EnumDescriptor(
  name='TriggerType',
  full_name='bogie.TriggerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_CONDITION_MET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=629,
)
_sym_db.RegisterEnumDescriptor(_TRIGGERTYPE)

TriggerType = enum_type_wrapper.EnumTypeWrapper(_TRIGGERTYPE)
UNKNOWN = 0
MANUAL = 1
TRIGGER_CONDITION_MET = 2



_VIBRATIONSENSORSAMPLES = _descriptor.Descriptor(
  name='VibrationSensorSamples',
  full_name='bogie.VibrationSensorSamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='bogie.VibrationSensorSamples.sensor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_sample_ts', full_name='bogie.VibrationSensorSamples.first_sample_ts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='bogie.VibrationSensorSamples.sample_rate', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='bogie.VibrationSensorSamples.samples', index=3,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=199,
)


_BOGIE_STEADYDRIVE = _descriptor.Descriptor(
  name='SteadyDrive',
  full_name='bogie.Bogie.SteadyDrive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max', full_name='bogie.Bogie.SteadyDrive.max', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rms', full_name='bogie.Bogie.SteadyDrive.rms', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=496,
)

_BOGIE_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='bogie.Bogie.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='bogie.Bogie.Position.lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon', full_name='bogie.Bogie.Position.lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alt', full_name='bogie.Bogie.Position.alt', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='bogie.Bogie.Position.speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=562,
)

_BOGIE = _descriptor.Descriptor(
  name='Bogie',
  full_name='bogie.Bogie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bogie.Bogie.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_type', full_name='bogie.Bogie.trigger_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_ts', full_name='bogie.Bogie.trigger_ts', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steady_drive', full_name='bogie.Bogie.steady_drive', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='bogie.Bogie.position', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_samples', full_name='bogie.Bogie.sensor_samples', index=5,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOGIE_STEADYDRIVE, _BOGIE_POSITION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=562,
)

_VIBRATIONSENSORSAMPLES.fields_by_name['first_sample_ts'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BOGIE_STEADYDRIVE.containing_type = _BOGIE
_BOGIE_POSITION.containing_type = _BOGIE
_BOGIE.fields_by_name['trigger_type'].enum_type = _TRIGGERTYPE
_BOGIE.fields_by_name['trigger_ts'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BOGIE.fields_by_name['steady_drive'].message_type = _BOGIE_STEADYDRIVE
_BOGIE.fields_by_name['position'].message_type = _BOGIE_POSITION
_BOGIE.fields_by_name['sensor_samples'].message_type = _VIBRATIONSENSORSAMPLES
DESCRIPTOR.message_types_by_name['VibrationSensorSamples'] = _VIBRATIONSENSORSAMPLES
DESCRIPTOR.message_types_by_name['Bogie'] = _BOGIE
DESCRIPTOR.enum_types_by_name['TriggerType'] = _TRIGGERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VibrationSensorSamples = _reflection.GeneratedProtocolMessageType('VibrationSensorSamples', (_message.Message,), {
  'DESCRIPTOR' : _VIBRATIONSENSORSAMPLES,
  '__module__' : 'bogie.v1.bogie_pb2'
  # @@protoc_insertion_point(class_scope:bogie.VibrationSensorSamples)
  })
_sym_db.RegisterMessage(VibrationSensorSamples)

Bogie = _reflection.GeneratedProtocolMessageType('Bogie', (_message.Message,), {

  'SteadyDrive' : _reflection.GeneratedProtocolMessageType('SteadyDrive', (_message.Message,), {
    'DESCRIPTOR' : _BOGIE_STEADYDRIVE,
    '__module__' : 'bogie.v1.bogie_pb2'
    # @@protoc_insertion_point(class_scope:bogie.Bogie.SteadyDrive)
    })
  ,

  'Position' : _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
    'DESCRIPTOR' : _BOGIE_POSITION,
    '__module__' : 'bogie.v1.bogie_pb2'
    # @@protoc_insertion_point(class_scope:bogie.Bogie.Position)
    })
  ,
  'DESCRIPTOR' : _BOGIE,
  '__module__' : 'bogie.v1.bogie_pb2'
  # @@protoc_insertion_point(class_scope:bogie.Bogie)
  })
_sym_db.RegisterMessage(Bogie)
_sym_db.RegisterMessage(Bogie.SteadyDrive)
_sym_db.RegisterMessage(Bogie.Position)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
