//
//Copyright © 2022 Ci4Rail GmbH <engineering@ci4rail.com>
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: bogie/v1/bogie.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerType int32

const (
	TriggerType_UNKNOWN               TriggerType = 0
	TriggerType_MANUAL                TriggerType = 1
	TriggerType_TRIGGER_CONDITION_MET TriggerType = 2
)

// Enum value maps for TriggerType.
var (
	TriggerType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MANUAL",
		2: "TRIGGER_CONDITION_MET",
	}
	TriggerType_value = map[string]int32{
		"UNKNOWN":               0,
		"MANUAL":                1,
		"TRIGGER_CONDITION_MET": 2,
	}
)

func (x TriggerType) Enum() *TriggerType {
	p := new(TriggerType)
	*p = x
	return p
}

func (x TriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_bogie_v1_bogie_proto_enumTypes[0].Descriptor()
}

func (TriggerType) Type() protoreflect.EnumType {
	return &file_bogie_v1_bogie_proto_enumTypes[0]
}

func (x TriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerType.Descriptor instead.
func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return file_bogie_v1_bogie_proto_rawDescGZIP(), []int{0}
}

type VibrationSensorSamples struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sensor id
	SensorId int32 `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	// first sample timestamp
	FirstSampleTs *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=first_sample_ts,json=firstSampleTs,proto3" json:"first_sample_ts,omitempty"`
	// sample rate in Hz
	SampleRate float64 `protobuf:"fixed64,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// the meaurement samples
	// unit: g
	Samples []float32 `protobuf:"fixed32,10,rep,packed,name=samples,proto3" json:"samples,omitempty"`
}

func (x *VibrationSensorSamples) Reset() {
	*x = VibrationSensorSamples{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bogie_v1_bogie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VibrationSensorSamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VibrationSensorSamples) ProtoMessage() {}

func (x *VibrationSensorSamples) ProtoReflect() protoreflect.Message {
	mi := &file_bogie_v1_bogie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VibrationSensorSamples.ProtoReflect.Descriptor instead.
func (*VibrationSensorSamples) Descriptor() ([]byte, []int) {
	return file_bogie_v1_bogie_proto_rawDescGZIP(), []int{0}
}

func (x *VibrationSensorSamples) GetSensorId() int32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *VibrationSensorSamples) GetFirstSampleTs() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSampleTs
	}
	return nil
}

func (x *VibrationSensorSamples) GetSampleRate() float64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *VibrationSensorSamples) GetSamples() []float32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

type Bogie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// bogie id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the trigger type
	TriggerType TriggerType `protobuf:"varint,2,opt,name=trigger_type,json=triggerType,proto3,enum=bogie.TriggerType" json:"trigger_type,omitempty"`
	// trigger timestamp
	TriggerTs *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=trigger_ts,json=triggerTs,proto3" json:"trigger_ts,omitempty"`
	// steady drive values at trigger moment
	SteadyDrive *Bogie_SteadyDrive `protobuf:"bytes,4,opt,name=steady_drive,json=steadyDrive,proto3" json:"steady_drive,omitempty"`
	// position at trigger moment
	Position *Bogie_Position `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	// the sensor samples
	SensorSamples []*VibrationSensorSamples `protobuf:"bytes,10,rep,name=sensor_samples,json=sensorSamples,proto3" json:"sensor_samples,omitempty"`
}

func (x *Bogie) Reset() {
	*x = Bogie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bogie_v1_bogie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bogie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bogie) ProtoMessage() {}

func (x *Bogie) ProtoReflect() protoreflect.Message {
	mi := &file_bogie_v1_bogie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bogie.ProtoReflect.Descriptor instead.
func (*Bogie) Descriptor() ([]byte, []int) {
	return file_bogie_v1_bogie_proto_rawDescGZIP(), []int{1}
}

func (x *Bogie) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bogie) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_UNKNOWN
}

func (x *Bogie) GetTriggerTs() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggerTs
	}
	return nil
}

func (x *Bogie) GetSteadyDrive() *Bogie_SteadyDrive {
	if x != nil {
		return x.SteadyDrive
	}
	return nil
}

func (x *Bogie) GetPosition() *Bogie_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bogie) GetSensorSamples() []*VibrationSensorSamples {
	if x != nil {
		return x.SensorSamples
	}
	return nil
}

type Bogie_SteadyDrive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max []float64 `protobuf:"fixed64,1,rep,packed,name=max,proto3" json:"max,omitempty"`
	Rms []float64 `protobuf:"fixed64,2,rep,packed,name=rms,proto3" json:"rms,omitempty"`
}

func (x *Bogie_SteadyDrive) Reset() {
	*x = Bogie_SteadyDrive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bogie_v1_bogie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bogie_SteadyDrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bogie_SteadyDrive) ProtoMessage() {}

func (x *Bogie_SteadyDrive) ProtoReflect() protoreflect.Message {
	mi := &file_bogie_v1_bogie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bogie_SteadyDrive.ProtoReflect.Descriptor instead.
func (*Bogie_SteadyDrive) Descriptor() ([]byte, []int) {
	return file_bogie_v1_bogie_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Bogie_SteadyDrive) GetMax() []float64 {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Bogie_SteadyDrive) GetRms() []float64 {
	if x != nil {
		return x.Rms
	}
	return nil
}

type Bogie_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat   float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon   float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt   float64 `protobuf:"fixed64,3,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed float64 `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *Bogie_Position) Reset() {
	*x = Bogie_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bogie_v1_bogie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bogie_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bogie_Position) ProtoMessage() {}

func (x *Bogie_Position) ProtoReflect() protoreflect.Message {
	mi := &file_bogie_v1_bogie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bogie_Position.ProtoReflect.Descriptor instead.
func (*Bogie_Position) Descriptor() ([]byte, []int) {
	return file_bogie_v1_bogie_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Bogie_Position) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Bogie_Position) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Bogie_Position) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Bogie_Position) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_bogie_v1_bogie_proto protoreflect.FileDescriptor

var file_bogie_v1_bogie_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x67, 0x69, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4,
	0x01, 0x0a, 0x16, 0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x02, 0x52, 0x07, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0xca, 0x03, 0x0a, 0x05, 0x42, 0x6f, 0x67, 0x69, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x35, 0x0a, 0x0c, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x2e, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x74, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54,
	0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x73, 0x74, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x2e,
	0x42, 0x6f, 0x67, 0x69, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x61, 0x64, 0x79, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x52, 0x0b, 0x73, 0x74, 0x65, 0x61, 0x64, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x2e, 0x42, 0x6f, 0x67, 0x69, 0x65, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x44, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x6f, 0x67, 0x69,
	0x65, 0x2e, 0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x1a, 0x31, 0x0a, 0x0b, 0x53, 0x74, 0x65, 0x61, 0x64,
	0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x03, 0x72, 0x6d, 0x73, 0x1a, 0x56, 0x0a, 0x08, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x2a, 0x41, 0x0a, 0x0b, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x52,
	0x49, 0x47, 0x47, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4d, 0x45, 0x54, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x62, 0x6f, 0x67, 0x69, 0x65, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bogie_v1_bogie_proto_rawDescOnce sync.Once
	file_bogie_v1_bogie_proto_rawDescData = file_bogie_v1_bogie_proto_rawDesc
)

func file_bogie_v1_bogie_proto_rawDescGZIP() []byte {
	file_bogie_v1_bogie_proto_rawDescOnce.Do(func() {
		file_bogie_v1_bogie_proto_rawDescData = protoimpl.X.CompressGZIP(file_bogie_v1_bogie_proto_rawDescData)
	})
	return file_bogie_v1_bogie_proto_rawDescData
}

var file_bogie_v1_bogie_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bogie_v1_bogie_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bogie_v1_bogie_proto_goTypes = []interface{}{
	(TriggerType)(0),               // 0: bogie.TriggerType
	(*VibrationSensorSamples)(nil), // 1: bogie.VibrationSensorSamples
	(*Bogie)(nil),                  // 2: bogie.Bogie
	(*Bogie_SteadyDrive)(nil),      // 3: bogie.Bogie.SteadyDrive
	(*Bogie_Position)(nil),         // 4: bogie.Bogie.Position
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_bogie_v1_bogie_proto_depIdxs = []int32{
	5, // 0: bogie.VibrationSensorSamples.first_sample_ts:type_name -> google.protobuf.Timestamp
	0, // 1: bogie.Bogie.trigger_type:type_name -> bogie.TriggerType
	5, // 2: bogie.Bogie.trigger_ts:type_name -> google.protobuf.Timestamp
	3, // 3: bogie.Bogie.steady_drive:type_name -> bogie.Bogie.SteadyDrive
	4, // 4: bogie.Bogie.position:type_name -> bogie.Bogie.Position
	1, // 5: bogie.Bogie.sensor_samples:type_name -> bogie.VibrationSensorSamples
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bogie_v1_bogie_proto_init() }
func file_bogie_v1_bogie_proto_init() {
	if File_bogie_v1_bogie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bogie_v1_bogie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VibrationSensorSamples); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bogie_v1_bogie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bogie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bogie_v1_bogie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bogie_SteadyDrive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bogie_v1_bogie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bogie_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bogie_v1_bogie_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bogie_v1_bogie_proto_goTypes,
		DependencyIndexes: file_bogie_v1_bogie_proto_depIdxs,
		EnumInfos:         file_bogie_v1_bogie_proto_enumTypes,
		MessageInfos:      file_bogie_v1_bogie_proto_msgTypes,
	}.Build()
	File_bogie_v1_bogie_proto = out.File
	file_bogie_v1_bogie_proto_rawDesc = nil
	file_bogie_v1_bogie_proto_goTypes = nil
	file_bogie_v1_bogie_proto_depIdxs = nil
}
